# Default values for loadgenerator

replicaCount: 1

image:
  repository: 10.10.10.240/library/loadgenerator
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name: ""

podAnnotations: {}

resources:
  limits:
    cpu: 4000m
    memory: 2048Mi
  requests:
    cpu: 2000m
    memory: 1024Mi

nodeSelector: {}
tolerations: []
affinity: {}

# Application specific configuration
baseURL: "http://10.10.10.220:30080"

# Command line arguments from main.go
config:
  debug: true
  threads: 1
  sleep: 1000
  # chain: ""
  # count: 1
